brand:
  name: John Lim Ji Xiong
menu-string: Menu

nav:
  - title: Services
    url: '#services'
  - title: Portfolio
    url: '#portfolio'
  - title: About
    url: '#about'
  - title: Team
    url: '#team'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; John Lim Ji Xiong 2019

social-buttons:
  - icon: fa fa-facebook
    url: '#'
  - icon: fa fa-linkedin
    url: '#'

quicklinks:

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
